# Generated by Django 5.1.2 on 2024-10-20 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destiny',
            old_name='location',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='destiny',
            name='name',
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('availability', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='accommodations/')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='tours.destiny')),
            ],
        ),
    ]
