# Generated by Django 5.1.2 on 2024-10-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_rename_location_destiny_country_remove_destiny_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_range', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='destinations/')),
            ],
        ),
    ]
