# Generated by Django 5.1.2 on 2024-10-20 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_attract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='attract')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('upload', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Attract',
        ),
        migrations.AlterField(
            model_name='destiny',
            name='image',
            field=models.ImageField(upload_to='destiny'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.destiny'),
        ),
    ]
