# Generated by Django 5.1.2 on 2024-10-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_attraction_delete_attract_alter_destiny_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='stay',
            new_name='destiny',
        ),
    ]
