# Generated by Django 5.1.2 on 2024-10-22 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_rename_stay_accommodation_destiny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.destiny'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(upload_to='accommodation/'),
        ),
    ]
