# Generated by Django 5.1.2 on 2024-10-28 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_destination_review_destiny_and_more'),
        ('tours', '0008_facility_roomimage_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destiny',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tours.destiny'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
