# Generated by Django 5.1.2 on 2024-10-28 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0004_delete_booking'),
        ('tours', '0008_facility_roomimage_delete_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.accommodation')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.destiny')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
