# Generated by Django 5.1.2 on 2024-10-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
